name: Trigger Github Page Update
on: push
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: WE GO
        run: | 
          rm -rf .github
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          ssh-add - <<< "${{ secrets.SSH_DEPLOY_KEY }}"
          git commit -a -m "rekt actions"
          git push git@github.com:oneacik/oneacik.github.io.git master --force
